---
- hosts: all
  vars_files: 
    - vars/vars.yaml
  remote_user: "{{ user }}"
  become: yes
  tasks:
  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/debian buster stable
  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
  - name: add userpermissions
    shell: "usermod -aG docker {{ user }}"

#Install Kubectl
  - name: add kubectl signing key
    get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  - name: add kubectl repo
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
  - name: Install kubectl
    apt:
      name: kubectl
      update_cache: yes

  - name: install python package manager
    apt:
      name: python3-pip
  
  - name: install python sdk
    become_user: "{{ user }}"
    pip:
      name:
        - docker
        - docker-compose    
